# Generated by Django 3.1.3 on 2021-09-06 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='created_at',
            field=models.DateField(default=1630919141.9384582),
        ),
    ]
