# Generated by Django 3.1.3 on 2021-09-24 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20210924_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='created_at',
            field=models.DateField(default=1632504103.232933),
        ),
        migrations.AlterField(
            model_name='rolepermissions',
            name='added_date',
            field=models.DateField(default=1632504103.2797563),
        ),
        migrations.AlterField(
            model_name='userpermission',
            name='expire_time',
            field=models.DateTimeField(default=1632504103.2797563, null=True),
        ),
        migrations.AlterField(
            model_name='userpermission',
            name='taken_time',
            field=models.DateField(default=1632504103.2797563),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='expire_time',
            field=models.DateTimeField(default=1632504103.2797563, null=True),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='taken_time',
            field=models.DateTimeField(default=1632504103.2797563),
        ),
    ]
