# Generated by Django 3.1.3 on 2021-09-24 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20210924_2021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrole',
            name='expire_time',
        ),
        migrations.RemoveField(
            model_name='userrole',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='userrole',
            name='taken_time',
        ),
        migrations.AlterField(
            model_name='account',
            name='created_at',
            field=models.DateField(default=1632504171.8614204),
        ),
        migrations.AlterField(
            model_name='rolepermissions',
            name='added_date',
            field=models.DateField(default=1632504171.9239492),
        ),
        migrations.AlterField(
            model_name='userpermission',
            name='expire_time',
            field=models.DateTimeField(default=1632504171.9239492, null=True),
        ),
        migrations.AlterField(
            model_name='userpermission',
            name='taken_time',
            field=models.DateField(default=1632504171.9239492),
        ),
    ]
